---
title: "InstaCart Exploratory Analysis: Products Analysis"
author: "Hoang Anh Thai Vu, Daniel Ochoa, Qiuhan Sun, April Choi"
date: "October 18, 2017"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "ExploratoryAnalysis_HTML_Output") })
output:
  bookdown::tufte_html2:
    number_sections: no
    split_by: none
    toc: no
  bookdown::html_document2:
    number_sections: no
    split_by: none
    toc: no
  bookdown::tufte_handout2:
    latex_engine: xelatex
    number_sections: no
    toc: no
---

This file provides some exploratory analysis of the InstaCart data.

```{r setup, include=FALSE}
library(tufte)
library(tidyverse)
library(ggplot2)
library(scales)
knitr::opts_chunk$set(tidy = FALSE, message=FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

# Reading in the data


```{r cache=TRUE}
aisles = read_csv("../Source/aisles.csv")
departments = read_csv("../Source/departments.csv")
products = read_csv("../Source/products.csv")
order_products_train = read_csv("../Source/order_products__train.csv")
```

# Preparing the data

Merging all product related configure

```{r cache=TRUE}
warehouse <- products%>%
  left_join(departments)%>%
  left_join(aisles)

inventory <- warehouse%>%
  group_by(department,aisle)%>%
  summarise(total=n())

orders_details_train <- left_join(order_products_train,products)

```

To be doing: Creating an adjacency matrix for co-appearance of aisles within an order --> Visualization with a network


